alter table DF_SIMPLE_DOC add constraint FK_DF_SIMPLE_DOC_COSTART_ID foreign key (COSTART_ID) references TEZISDIRECTORY_COST_ARTICLE(ID);
create index IDX_DF_SIMPLE_DOC_COSTART on DF_SIMPLE_DOC (COSTART_ID);
