--Insert permissions for entity tezisdirectory$CostArticle
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:create',0,(select id from sec_role where name='SimpleUser'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:update',0,(select id from sec_role where name='SimpleUser'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:delete',0,(select id from sec_role where name='SimpleUser'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:create',1,(select id from sec_role where name='Administrators'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:update',1,(select id from sec_role where name='Administrators'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:delete',1,(select id from sec_role where name='Administrators'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:create',1,(select id from sec_role where name='ReferenceEditor'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:update',1,(select id from sec_role where name='ReferenceEditor'));
INSERT INTO sec_permission (id,create_ts,created_by,version,update_ts,updated_by,delete_ts,deleted_by,PERMISSION_TYPE,target,value,role_id) VALUES (newid(),now(),'system',1,now(),null,null,null,20,'tezisdirectory$CostArticle:delete',1,(select id from sec_role where name='ReferenceEditor'));
