--$Id: 130522-1305-addColumnToCardACL.sql 9816 2013-05-23 09:21:28Z kozyaikin $
--Description:

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TS_CARD_ACL' AND COLUMN_NAME = 'DEPARTMENT_ID')
BEGIN
    ALTER TABLE TS_CARD_ACL ADD DEPARTMENT_ID uniqueidentifier;
END^

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'TS_CARD_ACL' AND CONSTRAINT_NAME = 'FK_TS_CARD_ACL_DF_DEPARTMENT')
BEGIN
    alter table TS_CARD_ACL add constraint FK_TS_CARD_ACL_DF_DEPARTMENT foreign key (DEPARTMENT_ID) references DF_DEPARTMENT(correspondent_id);
END^

IF NOT EXISTS(SELECT * FROM sysindexes WHERE name='IDX_TS_CARD_ACL_DF_DEPARTMENT')
BEGIN
    create index IDX_TS_CARD_ACL_DF_DEPARTMENT on TS_CARD_ACL(DEPARTMENT_ID);
END^