function com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset(){var Q='bootstrap',R='begin',S='gwt.codesvr.com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset=',T='gwt.codesvr=',U='com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset',qb='Failed to load ',rb='head',sb='meta',tb='name',ub='com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset::',vb='::',wb='gwt:property',xb='content',yb='=',zb='gwt:onPropertyErrorFn',Ab='Bad handler "',Bb='" for "gwt:onPropertyErrorFn"',Cb='gwt:onLoadErrorFn',Db='" for "gwt:onLoadErrorFn"',Eb='#',Fb='?',Gb='/',Hb='img',Ib='clear.cache.gif',Jb='baseUrl',Kb='com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset.nocache.js',Lb='base',Mb='//',Nb='ie11orHigher',Ob='MSIE',Pb='Trident',Qb='yes',Rb='no',Sb='locale',Tb='default',Ub='locale=',Vb=7,Wb='&',Xb='__gwt_Locale',Yb='_',Zb='Unexpected exception in locale detection, using default: ',$b='modernie',_b='none',ac='user.agent',bc='webkit',cc='trident',dc='safari',ec='msie',fc=10,gc=11,hc='ie10',ic=9,jc='ie9',kc=8,lc='ie8',mc='gecko',nc='gecko1_8',oc=2,pc=3,qc=4,rc='selectingPermutation',sc='com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset.devmode.js',tc='140CC3CBF2F989FBF496345E64B612B3',uc=':1',vc='ru',wc=':10',xc=':11',yc=':12',zc=':13',Ac=':14',Bc=':15',Cc=':16',Dc=':17',Ec=':18',Fc=':19',Gc=':2',Hc=':20',Ic=':21',Jc=':22',Kc=':23',Lc=':3',Mc=':4',Nc=':5',Oc=':6',Pc=':7',Qc=':8',Rc=':9',Sc=':',Tc='.cache.js',Uc='link',Vc='rel',Wc='stylesheet',Xc='href',Yc='loadExternalRefs',Zc='popupbutton/popupbutton.css',$c='googlemaps/styles.css',_c='animator/animator.css',ad='notifique/styles.css ',bd='end',cd='http:',dd='file:',ed='_gwt_dummy_',fd='__gwtDevModeHook:com.haulmont.thesis.web.toolkit.ui.ThesisWidgetset',gd='Ignoring non-whitelisted Dev Mode URL: ',hd=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__sendStats=t;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleName=U;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__errFn=null;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleBase=W;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__softPermutationId=X;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__computePropValue=null;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__getPropMap=null;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__installRunAsyncCode=function(){};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__gwtStartLoadingFragment=function(){return null};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__gwt_isKnownPropertyValue=function(){return false};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__errFn){n.onerror=function(){com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__errFn(pb,new Error(qb+code))}}r.getElementsByTagName(rb)[X].appendChild(n)}
com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__startLoadingFragment=function(a){return G(a)};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(sb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,db);if(j.indexOf(vb)>=X){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Jb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Lb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Nb]=function(){{var a=q.navigator.userAgent;if(a.indexOf(Ob)==-1&&a.indexOf(Pb)!=-1){return Qb}return Rb}};l[Nb]={no:X,yes:Y};m[Sb]=function(){var b=null;var c=Tb;try{if(!b){var d=location.search;var e=d.indexOf(Ub);if(e>=X){var f=d.substring(e+Vb);var g=d.indexOf(Wb,e);if(g<X){g=d.length}b=d.substring(e+Vb,g)}}if(!b){b=__gwt_getMetaProperty(Sb)}if(!b){b=q[Xb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Sb,b)){var h=b.lastIndexOf(Yb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Zb+a)}q[Xb]=c;return b||Tb};l[Sb]={'default':X,ru:Y};m[$b]=function(){{var a=q.navigator.userAgent;if(a.indexOf(Ob)==-1&&a.indexOf(Pb)!=-1){return Qb}return _b}};l[$b]={none:X,yes:Y};m[ac]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(bc)!=-1&&a.indexOf(cc)==-1}())return dc;if(function(){return a.indexOf(ec)!=-1&&(b>=fc&&b<gc)}())return hc;if(function(){return a.indexOf(ec)!=-1&&(b>=ic&&b<gc)}())return jc;if(function(){return a.indexOf(ec)!=-1&&(b>=kc&&b<gc)}())return lc;if(function(){return a.indexOf(mc)!=-1||b>=gc}())return nc;return db};l[ac]={gecko1_8:X,ie10:Y,ie8:oc,ie9:pc,safari:qc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__computePropValue=n;q.__gwt_activeModules[U].bindings=com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__getPropMap;t(Q,rc);if(s()){return G(sc)}var o;try{k([Rb,Tb,_b,nc],tc);k([Rb,Tb,Qb,nc],tc+uc);k([Rb,vc,_b,jc],tc+wc);k([Rb,vc,_b,dc],tc+xc);k([Qb,Tb,_b,nc],tc+yc);k([Qb,Tb,Qb,nc],tc+zc);k([Qb,Tb,_b,hc],tc+Ac);k([Qb,Tb,_b,lc],tc+Bc);k([Qb,Tb,_b,jc],tc+Cc);k([Qb,Tb,_b,dc],tc+Dc);k([Qb,vc,_b,nc],tc+Ec);k([Qb,vc,Qb,nc],tc+Fc);k([Rb,Tb,_b,hc],tc+Gc);k([Qb,vc,_b,hc],tc+Hc);k([Qb,vc,_b,lc],tc+Ic);k([Qb,vc,_b,jc],tc+Jc);k([Qb,vc,_b,dc],tc+Kc);k([Rb,Tb,_b,lc],tc+Lc);k([Rb,Tb,_b,jc],tc+Mc);k([Rb,Tb,_b,dc],tc+Nc);k([Rb,vc,_b,nc],tc+Oc);k([Rb,vc,Qb,nc],tc+Pc);k([Rb,vc,_b,hc],tc+Qc);k([Rb,vc,_b,lc],tc+Rc);o=i[n(Nb)][n(Sb)][n($b)][n(ac)];var p=o.indexOf(Sc);if(p!=-1){j=parseInt(o.substring(p+Y),fc);o=o.substring(X,p)}}catch(a){}com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__softPermutationId=j;return G(o+Tc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Uc);b.setAttribute(Vc,Wc);b.setAttribute(Xc,G(a));r.getElementsByTagName(rb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Yc,R);c(Zc);c($c);c(_c);c(ad);t(Yc,bd)}
D();com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleBase=F();v[U].moduleBase=com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==cd||q.location.protocol==dd);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=ed;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=fd;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(gd+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+hd]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(rb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,bd);C(J);return true}
com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset.succeeded=com_haulmont_thesis_web_toolkit_ui_ThesisWidgetset();