ALTER TABLE WF_ATTACHMENT add CONTRACTOR_ID uuid^

INSERT INTO WF_ATTACHMENT (ID,CREATE_TS,CREATED_BY,VERSION,
                             UPDATE_TS,UPDATED_BY,DELETE_TS,DELETED_BY, NAME, COMMENT, FILE_ID, CONTRACTOR_ID, TYPE)
SELECT ID,CREATE_TS,CREATED_BY,VERSION, UPDATE_TS,UPDATED_BY,DELETE_TS,
       DELETED_BY, NAME, COMMENT, FILE_ID, CONTRACTOR_ID, 'D'
FROM DF_CONTRACTOR_ATTACHMENT^

DROP TABLE DF_CONTRACTOR_ATTACHMENT^