sp_rename DF_RESOLUTION_WAITING_COMPLETE, DF_SUB_CARD_INFO;

alter table DF_SUB_CARD_INFO drop constraint FK_DF_RESOLUTION_WAITING_COMPLETE_CARD;
alter table DF_SUB_CARD_INFO drop constraint FK_DF_RESOLUTION_WAITING_COMPLETE_CARD_TO_RESOLUTION;
alter table DF_SUB_CARD_INFO drop constraint FK_DF_RESOLUTION_WAITING_ASSIGNMENT;

exec sp_rename 'DF_SUB_CARD_INFO.CARD_ID', 'SUB_CARD_ID', 'COLUMN';
exec sp_rename 'DF_SUB_CARD_INFO.CARD_TO_RESOLUTION_ID', 'PARENT_CARD_ID', 'COLUMN';
exec sp_rename 'DF_SUB_CARD_INFO.ASSIGNMENT_ID', 'RESOLUTION_ASSIGNMENT_ID', 'COLUMN';
alter table DF_SUB_CARD_INFO add SUB_CARD_CREATED_ASSIGNMENT_ID uniqueidentifier;

alter table DF_SUB_CARD_INFO add constraint FK_DF_SUB_CARD_INFO_SUB_CARD foreign key (SUB_CARD_ID) references WF_CARD(ID);
alter table DF_SUB_CARD_INFO add constraint FK_DF_SUB_CARD_INFO_PARENT_CARD foreign key (PARENT_CARD_ID) references WF_CARD(ID);
alter table DF_SUB_CARD_INFO add constraint FK_DF_SUB_CARD_INFO_RESOLUTION_ASSIGNMENT foreign key (RESOLUTION_ASSIGNMENT_ID) references WF_ASSIGNMENT(ID);
alter table DF_SUB_CARD_INFO add constraint FK_DF_SUB_CARD_INFO_SUB_CARD_CREATED_ASSIGNMENT foreign key (SUB_CARD_CREATED_ASSIGNMENT_ID) references WF_ASSIGNMENT(ID);
alter table DF_SUB_CARD_INFO add TYPE varchar(1);

update DF_SUB_CARD_INFO set TYPE='R';